# -*- coding: utf-8 -*-
"""jogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16w21jzMeDYMjxGRMxuYlLTIkqTa9ALhD
"""

import random


class Personagem:

  def __init__(self, nome, vida, nivel) -> None:
    self.__nome = nome
    self.__vida = vida
    self.__nivel = nivel
    return

  def get_nome(self):
    return self.__nome

  def get_vida(self):
    return self.__vida

  def get_nivel(self):
    return self.__nivel

  def exibir_detalhes(self):
    return f"Nome: {self.get_nome()}\nVida: {self.get_vida()}\nNível: {self.get_nivel()}"

  def receber_dano(self,dano):
    self.__vida -= dano
    if self.__vida < 0:
      self.__vida = 0

  def atacar(self, alvo):
    dano = random.randint(self.get_nivel() * 2 , self.get_nivel() * 4)
    alvo.receber_dano(dano)
    print(f"{self.get_nome()} atacou {alvo.get_nome()} e causou {dano} de dano!")




class Heroi(Personagem):
  def __init__(self, nome, vida, nivel, forca, habilidade) -> None:
    super().__init__(nome, vida, nivel)
    self.__habilidade = habilidade
    return

  def get_habilidade(self):
    return self.__habilidade

  def exibir_detalhes(self):
    return f"""{super().exibir_detalhes()}\nHabilidade: {self.get_habilidade()} """

  def ataque_especial(self, alvo):
    dano = random.randint(self.get_nivel() * 5 , self.get_nivel() * 8)
    alvo.receber_dano(dano)
    print(f"{self.get_nome()} usou o ataque especial e causou {dano} de dano!")

class Inimigo(Personagem):
  def __init__(self, nome, vida, nivel, tipo) -> None:
    super().__init__(nome, vida, nivel)
    self.__tipo = tipo
    return

  def get_tipo(self):
    return self.__tipo

  def exibir_detalhes(self):
    return f"""{super().exibir_detalhes()}\nTipo: {self.get_tipo()} """


class Jogo:
  def __init__(self) -> None:
    self.heroi = Heroi("Héroi", 100, 5, 20, "Super Força")
    self.inimigo = Inimigo("Inimigo", 100, 5, "Monstro")


  def iniciar_batalha(self):
    print("Iniciando uma batalha...")
    while self.heroi.get_vida() > 0 and self.inimigo.get_vida() > 0:
      print("Detalhes do personagem:")
      print(self.heroi.exibir_detalhes())
      print()
      print(self.inimigo.exibir_detalhes())

      input("Pressione Enter para atacar...")
      escolha = input("Escolha (1 - Ataque Normal, 2 - Ataque Especial):")
      print()

      if escolha == '1':
        self.heroi.atacar(self.inimigo)
      elif escolha == '2':
        self.heroi.ataque_especial(self.inimigo)
      else:
        print("Opção inválida. Tente novamente.")

      if self.inimigo.get_vida() > 0:
        self.inimigo.atacar(self.heroi)
        print()

    if self.heroi.get_nivel() > 0:
      print("Parabéns! Você derrotou o inimigo!")
    else:
      print("Infelizmente, você foi derrotado.")

jogo = Jogo()
jogo.iniciar_batalha()